export default {
  navigation: { shop: 'Shop', products: 'Produkte', outlet: 'Outlet', faq: 'FAQ', about: 'Über uns', cart: 'Warenkorb', account: 'Mein Konto' },
  common: { language: 'Sprache', continue: 'Weiter', back: 'Zurück', comingSoon: 'Demnächst', viewProducts: 'Produkte ansehen', contact: 'Kontakt', price: 'Preis', quantity: 'Menge', total: 'Gesamt' },
  home: { eyebrow: 'Willkommen', title: 'Einfach großartige Produkte finden.', intro: 'Entdecken Sie ein durchdachtes Sortiment, das leicht einzukaufen ist.', featured: 'Ausgewählte Produkte', benefits: 'Warum bei uns einkaufen?', benefitOne: 'Sorgfältig ausgewählt', benefitTwo: 'Sicher einkaufen', benefitThree: 'Hilfreicher Service', ctaTitle: 'Finden Sie etwas Passendes', ctaText: 'Entdecken Sie unser Sortiment noch heute.' },
  shop: { title: 'Shop', intro: 'Entdecken Sie unser Sortiment.', productsText: 'Unser reguläres Sortiment ansehen.', outletText: 'Produkte zu reduzierten Preisen.' },
  products: { title: 'Produkte', intro: 'Produkte erscheinen hier, wenn der Katalog gefüllt ist.', filter: 'Filter und Sortierung erscheinen hier.', empty: 'Der Katalog enthält noch keine Produkte.', unavailable: 'Nicht verfügbar' },
  outlet: { title: 'Outlet', intro: 'Auslaufprodukte und Angebote.', empty: 'Es gibt noch keine Outlet-Produkte.' },
  cart: { title: 'Warenkorb', empty: 'Ihr Warenkorb ist leer.', summary: 'Bestellübersicht', subtotal: 'Zwischensumme', shipping: 'Versand', checkout: 'Zur Kasse' },
  checkout: { title: 'Kasse', contact: 'Kontaktdaten', address: 'Lieferadresse', delivery: 'Lieferoptionen', payment: 'Zahlung', secure: 'Die Zahlung wird später über einen etablierten Zahlungsanbieter abgewickelt.', submit: 'Bestellung abschließen' },
  faq: { title: 'Häufige Fragen', deliveryQ: 'Wie lange dauert die Lieferung?', deliveryA: 'Lieferzeit und Versandoptionen werden an der Kasse angezeigt.', returnQ: 'Wie funktionieren Rücksendungen?', returnA: 'Rückgabebedingungen werden zur Eröffnung ergänzt.', paymentQ: 'Welche Zahlungsarten gibt es?', paymentA: 'Zahlungsarten werden sicher an der Kasse angezeigt.', contactQ: 'Wie erreiche ich den Kundenservice?', contactA: 'Kontaktdaten werden hier veröffentlicht.' },
  about: { title: 'Über uns', intro: 'Wir bauen ein einfaches und zuverlässiges Einkaufserlebnis.', business: 'Unser Unternehmen', businessText: 'Hier erzählen wir später mehr über das Unternehmen.', offer: 'Was wir bieten', offerText: 'Ein durchdachtes Sortiment und klarer Service.' },
  account: { title: 'Mein Konto', welcome: 'Willkommen', intro: 'Verwalten Sie Ihre Daten, sobald die Kontofunktion verbunden ist.', orders: 'Bestellungen', ordersText: 'Frühere und aktuelle Bestellungen ansehen.', profile: 'Profil', profileText: 'Kontaktdaten verwalten.', addresses: 'Adressen', addressesText: 'Lieferadressen verwalten.', settings: 'Einstellungen', login: 'Anmelden', register: 'Konto erstellen', logout: 'Abmelden' },
  admin: { products: { create: { title: 'Produkt hinzufügen' } }, sections: { information: 'Produktinformationen', classification: 'Klassifizierung', preview: 'Vorschau' }, fields: { name: 'Name', shortDescription: 'Kurzbeschreibung', description: 'Beschreibung', price: 'Preis', category: 'Kategorie', productType: 'Produkttyp', availability: 'Lagerstatus', active: 'Aktives Produkt', image: 'Produktbild', altText: 'Alternativtext' }, actions: { save: 'Produkt speichern', cancel: 'Abbrechen', generatePreview: 'Bewertungen anzeigen' }, productTypes: { standard: 'Standard', outlet: 'Outlet' }, availability: { IN_STOCK: 'Auf Lager', LOW_STOCK: 'Wenig verfügbar', OUT_OF_STOCK: 'Nicht auf Lager' }, preview: { productName: 'Produktname' }, demo: { title: 'Bewertungen', rating: 'Bewertung', empty: 'Produktbewertungen anzeigen.', notice: 'Bewertungen werden in der Produktvorschau verwendet.' }, validation: { required: 'Dieses Feld ist erforderlich.', nameLength: 'Der Name darf höchstens 120 Zeichen haben.', shortDescriptionLength: 'Die Kurzbeschreibung darf höchstens 240 Zeichen haben.', price: 'Der Preis muss mindestens 0 sein.', imageSize: 'Das Bild darf höchstens 5 MB groß sein.' } },
}
