export default {
  navigation: { shop: 'Shop', products: 'Products', outlet: 'Outlet', faq: 'FAQ', about: 'About us', cart: 'Cart', account: 'My account' },
  common: { language: 'Language', continue: 'Continue', back: 'Back', comingSoon: 'Coming soon', viewProducts: 'View products', contact: 'Contact us', price: 'Price', quantity: 'Quantity', total: 'Total' },
  home: { eyebrow: 'Welcome', title: 'A simpler place for great products.', intro: 'Discover a considered assortment that is easy to shop from.', featured: 'Featured products', benefits: 'Why shop with us?', benefitOne: 'Carefully selected', benefitTwo: 'Secure shopping', benefitThree: 'Helpful service', ctaTitle: 'Find something for you', ctaText: 'Start exploring the assortment today.' },
  hero: { title: 'Welcome to NORTHPOINT', text: 'Pens with personality – for ideas that deserve to be written down.' },
  reviews: { title: 'What our customers say', previous: 'Show previous reviews', next: 'Show more reviews' },
  shop: { title: 'Shop', intro: 'Explore our assortment.', productsText: 'See our regular assortment.', outletText: 'Products at reduced prices.' },
  products: { title: 'Products', intro: 'Products appear here once the catalogue is populated.', filter: 'Filters and sorting will appear here.', empty: 'There are no products in the catalogue yet.', unavailable: 'Unavailable' },
  outlet: { title: 'Outlet', intro: 'Discontinued products and offers.', empty: 'There are no outlet products yet.' },
  cart: { title: 'Cart', empty: 'Your cart is empty.', summary: 'Order summary', subtotal: 'Subtotal', shipping: 'Shipping', checkout: 'Continue to checkout' },
  checkout: { title: 'Checkout', contact: 'Contact details', address: 'Delivery address', delivery: 'Delivery options', payment: 'Payment', secure: 'Payment will later be handled by an established payment provider.', submit: 'Place order' },
  faq: {
    title: 'Frequently asked questions', q1: 'Which pen should I choose? There are like a thousand?!', a1: 'Relax, we have your back. For quick, simple writing, choose a ballpoint pen. For smooth ink flow, try a gel pen. For a cosy author feeling, choose a fountain pen.', q2: 'Why do I need a good pen?', a2: 'Life is too short for pens that skip, smudge or stop in the middle of an important sentence. A good pen makes writing nicer.', q3: 'Can I have too many pens?', a3: 'Technically… yes. But we choose not to interfere. “I needed a new pen” is a perfectly reasonable explanation.', q4: 'My pen has run out of ink. Is it over?', a4: 'Absolutely not! Many of our pens can use refills, so give your pen a second chance. ❤️', q5: 'Which pen writes the fastest?', a5: 'The one closest to you when you need it. 😉 Writing feel depends on type, nib and ink, and we are happy to help.', q6: 'Are your pens only for people with neat handwriting?', a6: 'Not at all! Our pens do not judge handwriting, even if yours looks like a doctor’s notes.', q7: 'Can I give a pen as a gift?', a7: 'Absolutely! A fine pen is a classic, useful gift for birthdays, graduation, a new job or someone who has everything.', q8: 'What if I buy the wrong pen?', a8: 'No panic. If it meets our return conditions, you can return it and perhaps find your perfect pen next time.', q9: 'What if my pen arrives damaged?', a9: 'That is unfortunate, but we will sort it out. Contact us as soon as possible and we will help.', q10: 'How many pens should I order?', a10: 'There is no scientific maximum. We recommend at least two: one to write with and one to lose. A third is common sense.',
  },
  about: {
    title: 'About us', subtitle: 'Four people with far too many pens.', eyebrow: 'It all started with one simple question', question: 'How hard can it really be to find a truly good pen?', answer: 'Apparently, quite hard.',
    introOne: 'We are four people with different personalities, handwriting and opinions about the best pen. The one thing we agree on is that a good pen makes writing more fun.', introTwo: 'That is why we started our pen shop.', introThree: 'We look for pens that feel good in the hand, write beautifully and keep their promises. Pens for meetings, big ideas, notes, shopping lists and brilliant thoughts that disappear unless you write them down.',
    visionLabel: 'Our vision ✍️', visionTitle: 'We want to make the pen a little less forgotten.', visionOne: 'In a world where we write on phones, talk to AI and send emoji messages, there is something special about putting pen to paper.', visionTwo: 'Our vision is simple: more good pens in more hands. We want you to find a new favourite, whether you write three words a day or fill notebooks.',
    teamLabel: 'So who are we?', teamTitle: 'Four pen nerds with one shared problem.', teamIntro: 'None of us can resist trying a new pen.', teamOne: 'One of us hunts for quality.', teamTwo: 'Another hunts for great design.', teamThree: 'A third keeps track of what actually has to work.', teamFour: 'The fourth still says “do we really need more pens?” before ordering more pens.',
    closingOne: 'Together we choose the assortment, test products and try to make the world of pens simpler, more fun and better.', closingTwo: 'And yes – we still have a far too large pen collection at the office. We call it research.', closingTitle: 'Welcome to our little corner of the pen world.', closingThree: 'We hope you find a pen you like a little too much. That is exactly how it should be.',
  },
  account: { title: 'My account', welcome: 'Welcome', intro: 'Manage your details when account functionality is connected.', orders: 'Orders', ordersText: 'View previous and current orders.', profile: 'Profile', profileText: 'Manage contact details.', addresses: 'Addresses', addressesText: 'Manage delivery addresses.', settings: 'Settings', login: 'Log in', register: 'Create account', logout: 'Log out' },
  admin: { products: { create: { title: 'Add product' } }, sections: { information: 'Product information', classification: 'Classification', preview: 'Preview' }, fields: { name: 'Name', shortDescription: 'Short description', description: 'Description', price: 'Price', category: 'Category', productType: 'Product type', availability: 'Availability', active: 'Active product', image: 'Product image', altText: 'Alt text' }, actions: { save: 'Save product', cancel: 'Cancel', generatePreview: 'Show reviews' }, productTypes: { standard: 'Standard', outlet: 'Outlet' }, availability: { IN_STOCK: 'In stock', LOW_STOCK: 'Low stock', OUT_OF_STOCK: 'Out of stock' }, preview: { productName: 'Product name' }, demo: { title: 'Reviews', rating: 'Rating', empty: 'Show product reviews.', notice: 'Reviews are used in the product preview.' }, validation: { required: 'This field is required.', nameLength: 'The name may have at most 120 characters.', shortDescriptionLength: 'Short description may have at most 240 characters.', price: 'Price must be 0 or higher.', imageSize: 'Image may be at most 5 MB.' } },
}
